wip: fix crash due to null pointer because block element was not copied and copy() returned always null
Crash used to report following:

java.lang.NullPointerException: Attempt to invoke virtual method 'void com.icst.logic.lib.view.LayerBeanView.setLayerPosition(int)' on a null object reference
at com.icst.logic.block.view.RegularBlockBeanView.addLayers(RegularBlockBeanView.java:106)
at com.icst.logic.block.view.RegularBlockBeanView.init(RegularBlockBeanView.java:76)
at com.icst.logic.block.view.RegularBlockBeanView.<init>(RegularBlockBeanView.java:71)
at com.icst.logic.utils.ActionBlockUtils.getBlockView(ActionBlockUtils.java:47)
at com.icst.logic.lib.view.ActionBlockDropZoneView.addBlockBeans(ActionBlockDropZoneView.java:142)
at com.icst.logic.lib.view.ActionBlockDropZoneView.addActionBlocksBeans(ActionBlockDropZoneView.java:124)
at com.icst.logic.editor.view.LogicEditorView.dropBlock(LogicEditorView.java:206)
at com.icst.logic.editor.view.LogicEditorView.dropDraggingView(LogicEditorView.java:249)
at com.icst.logic.listener.DraggableTouchListener.onTouch(DraggableTouchListener.java:170)
at android.view.View.dispatchTouchEvent(View.java:13501)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3135)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2789)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3141)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2803)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3163)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2803)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3141)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2803)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3141)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2803)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3141)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2803)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3141)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2803)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3141)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2803)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3141)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2803)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3141)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2803)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3141)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2803)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3141)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2803)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3141)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2803)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3141)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2803)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3141)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2803)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3141)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2803)
at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:496)
at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1853)
at android.app.Activity.dispatchTouchEvent(Activity.java:4059)
at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:70)
at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:454)
at android.view.View.dispatchPointerEvent(View.java:13775)
at android.view.ViewRootImpl.processPointerEvent(ViewRootImpl.java:5813)
at android.view.ViewRootImpl.onProcess(ViewRootImpl.java:5604)
at android.view.ViewRootImpl.deliver(ViewRootImpl.java:5101)
at android.view.ViewRootImpl.onDeliverToNext(ViewRootImpl.java:5154)
at android.view.ViewRootImpl.forward(ViewRootImpl.java:5120)
at android.view.ViewRootImpl.forward(ViewRootImpl.java:5260)
at android.view.ViewRootImpl.apply(ViewRootImpl.java:5128)
at android.view.ViewRootImpl.apply(ViewRootImpl.java:5317)
at android.view.ViewRootImpl.deliver(ViewRootImpl.java:5101)
at android.view.ViewRootImpl.onDeliverToNext(ViewRootImpl.java:5154)
at android.view.ViewRootImpl.forward(ViewRootImpl.java:5120)
at android.view.ViewRootImpl.apply(ViewRootImpl.java:5128)
at android.view.ViewRootImpl.deliver(ViewRootImpl.java:5101)
at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7944)
at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7913)
at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7864)
at android.view.ViewRootImpl.onInputEvent(ViewRootImpl.java:8090)
at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:260)
at android.os.MessageQueue.nativePollOnce(Native Method)
at android.os.MessageQueue.next(MessageQueue.java:336)
at android.os.Looper.loop(Looper.java:182)
at android.app.ActivityThread.main(ActivityThread.java:7563)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit.run(RuntimeInit.java:539)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:994)